Scapture-official/Scapture-Client

.eslintrc.cjs
.gitignore
package-lock.json
package.json
src/apis/api/stadium.api.tsx
src/apis/dto/common.response.tsx
src/apis/utils/instance.tsx

- close #30 
- 디렉토리 구조는 다음과 같이 구성하였다.
<br/><br/>
- api 폴더에서는 api 카테고리 별로 파일을 생성하고 그 안에서 sub task별로 api를 작성한다.
예시)
<br/><br/>
- dotenv를 설치하여 BASE_URL에 사용되는 서버의 ip와 port를 따로 작성하였다.
.env 파일의 내용은 `노션을 참고`한다.
- 현재 임시로 공통 인터페이스를 3가지로 작성하였다.
1. 일반 api
2. 인증된 유저를 위한 auth api
3. 인증된 유저의 파일 전송을 위한 form data 형식의 auth api

🚩 API 통신 관련 코드 작성

---

src/DevTerminal.tsx
src/Page/Footer/components/Footer.tsx
src/Page/Header/components/Header.tsx
src/Page/Header/scss/header.module.scss

- close # Issue Number
- css를 develop에서 master로 병합하기 위한 PR
- 전체적인 css를 검토하고 필요한 task를 선정 및 분리

전체적인 페이지를 검토하고 css를 확인해 본다.

---

index.html
src/Page/MyPage/components/MyPage.tsx
src/Page/MyPage/functions/function.ts
src/Page/Reservation/functions/function.ts
src/Page/Video/components/Video.tsx
src/Page/Video/functions/function.ts

- close #65 
- #66 pr conflict를 해결하기 위한 pr

[Merge] conflict 해결을 위한 pr

---

src/Page/Community/components/Comment.tsx
src/Page/Community/components/Community.tsx
src/Page/Community/components/PopularVideoList.tsx
src/Page/Community/components/VideoHeart.tsx
src/Page/Reservation/components/Reservation.tsx
src/Page/Video/components/Video.tsx
src/apis/api/community.api.tsx

- close #91 
- 인기동영상 클릭시 동영상 보이게 수정
- 영상 좋아요 기능 에러 해결

Community 페이지 인기 동영상 변경

---

src/Page/Reservation/components/ReservationList.tsx
src/Page/Video/components/Video.tsx
src/common/functions/ModalFunction.ts

- close #96 
- ⚠ api res 기준으로 모달창 활성화
- ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화
- ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화
- ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화
- ~community 하트 클릭 시 로그인 모달 활성화~
- ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화
- ~community 댓글 클릭 시 로그인 모달 활성화~
- ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화
- video.tsx에서 처럼 hanlding이 되어 있는 함수 또는 로그인 필요 조건이 충족되어 있는 코드에선 원할하게 로그인 모달이 동작하는 것을 확인 할 수 있었다.
```
if (downloadResponse.status === 200) {
... 이하 생략...
} else {
alert('로그인이 필요합니다.');
modalNotice(loginModalRef);
}
} else {
alert('다운로드 권한 부여에 실패했습니다.');
modalNotice(loginModalRef);
}
...
```
Modal 컴포넌트를 사용하는 조건은 다음과 같다. 
- LoginModal 컴포넌트 import
- `Header/scss/login-modal.module.scss` 파일 import
- AUTH_URLS 객체 생성
```
const AUTH_URLS = {
kakao: KAKAO_AUTH_URL,
google: GOOGLE_AUTH_URL, …
```

Modal 페이지 활성화 페이지 점검 및 검토

---

src/Page/Community/components/Comment.tsx
src/Page/Community/components/Community.tsx
src/Page/Community/scss/community.module.scss
src/Page/MyPage/EditProfile/components/EditProfile.tsx
src/Page/MyPage/MyPage/components/MyPageModal.tsx
src/apis/api/mypage.api.tsx

🐛 Eslint 에러 해결

---

src/Page/MyPage/EditProfile/components/EditProfile.tsx
src/Page/MyPage/MyPage/components/MyPage.tsx

- close #108 
- ⚠naver state 구현 
- ⚠Header 영역 로그인 시 사용자 이름 전환 디벨롭
- ⚠naver state 구현 
generaState 함수를 구현했으나 정상작동하지 않음, 레퍼런스가 부족 해당 이슈를 파서 개발을 진행함이 옳다고 판단
- ⚠Header 영역 로그인 시 사용자 이름 전환 디벨롭
해당영역이 로그인 되었을 때 바로 로그인으로 전환되지 않는다. 정확한 판단을 위해 login.api 또는 useAtuh를 수정했지만 interface 보완이 필요하다. 다시 점검 필요

MyPage에서 Edit 페이지 편집 완료 후 업데이트 되지 않는 부분 수정

---

src/Page/MyPage/MyPage/components/MyPage.tsx
src/Page/MyPage/MyPage/scss/my-page.module.scss

- close #117 
- 특정 페이지에서 css가 깨지는 현상이 있어서 검토 및 수정

MyPage css 변경 및 수정

---

index.html
src/Page/Header/components/LoginModal.tsx

- close #126 
- head 태그에 사이트 설명과 상단에 나오게 지정하였다.
자세한 내용은 [링크](https://support.google.com/webmasters/answer/9008080#domain_name_verification&zippy=%2C%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%9D%B4%EB%A6%84-%EA%B3%B5%EA%B8%89%EC%97%85%EC%B2%B4)를 참고한다.

구글 상단에 나오게 설정하기

---

index.html

- close #125 
- Google Adsense를 위한 메타데이터 적용을 하였다.

Google Adsense를 이용하여 광고 삽입

---

src/Page/Community/components/Community.tsx
src/Page/Video/components/Video.tsx

- close #129 
- S3를 사용하는 경우 url 숨기기
url을 변경하는 방법으로 blob을 사용하였다.
- video의 경우 control 바에서 다운로드 버튼 없애기
`controlsList="nodownload"` video 태그에 해당 속성을 넣어줌으로써 해결하였다.
- 개발자 도구에서의 Url로 파일 접근 막기
video 가 로드된 시점에서 `URL.revokeObjectURL(url);` 을 통해 blob url을 해체하여 접근하지 못하도록 하였지만 이를 사용하게 될 경우 영상이 전부 로드되지 않아 1초 후에는 재생이 되지 않는 문제가 발생했다.
- 마우스 오른쪽 클릭으로 다운로드 금지하기
이는 `onContextMenu={e => e.preventDefault()}` 코드를 video 태그 속성으로 넣어주면 해결할 수 있었지만 개발자 도구에서 disable javascript를 사용한다면 다운로드가 가능하다.

파일 다운로드 방지

---

src/Page/MyPage/MyPage/components/MyPage.tsx
src/Page/MyPage/MyReservation/components/MyReservation.tsx

빌드를 위한 에러 해결

---

src/Page/Stadium/components/Stadium.tsx

- close #163 
- Stadium.tsx useState 에러 해결

Stadium.tsx useState 에러 해결

---

src/Page/Community/components/BookMark.tsx
src/Page/Community/components/Comment.tsx
src/Page/Community/components/Community.tsx
src/Page/Community/components/Heart.tsx
src/Page/Community/components/VideoHeart.tsx
src/Page/Video/components/BookMark.tsx
src/Page/Video/components/Heart.tsx
src/Page/Video/components/Video.tsx

- close #165 
- 이전에 이미지를 클릭해야 좋아요나 북마크가 눌리는 현상이 있어 이를 감싸고 있는 li 태그에 onClick 속성을 넣어주었다.

Heart 및 BookMark 변경

---

src/Page/Community/components/Community.tsx
src/Page/Header/components/Header.tsx
src/Page/Video/components/Video.tsx
src/apis/utils/instance.tsx
src/common/functions/Share.ts
src/common/functions/copyToClipBoard.ts

- close #167 
- 일부 디자인 수정
- 토큰 만료시 제거 기능 추가

일부 디자인 수정 및 토큰 만료시 제거 기능 추가

---

src/Page/Main/components/Main.tsx
src/Page/Reservation/components/ReservationList.tsx
src/Page/Reservation/components/ReservationModal.tsx
src/Page/Reservation/scss/reservation.module.scss
src/Page/Stadium/components/VideoList.tsx
src/Page/Video/scss/video.module.scss

- close #167 
- 예약하기 부분 디자인 수정
- 일부 디자인 변경

예약하기 부분 디자인 수정 및 일부 디자인 변경

---

src/Page/Community/components/Comment.tsx
src/Page/Community/components/Community.tsx
src/Page/Header/scss/header.module.scss
src/apis/utils/instance.tsx

- close #167 
- 댓글창 로그인 검사
-  일부 디자인 변경
- x

댓글창 로그인 검사 및 일부 디자인 변경

---

src/Page/MyPage/MyPage/components/SubscribeModal.tsx
src/Page/MyPage/MyPage/components/UserPage.tsx
src/Page/MyPage/MyReservation/components/MyReservation.tsx
src/Page/MyPage/MyReservation/scss/my-reservation.module.scss
src/Page/MyPage/dto/atom.interface.tsx
src/apis/dto/myPage.dto.tsx

- close #167
- 예약 내역 리스트 에러 테스트

예약 내역 리스트 에러 테스트

---

src/Page/MyPage/Atom/atom.tsx

EndDate 버그 해결

---

src/Page/MyPage/EditProfile/components/EditProfile.tsx
src/Page/MyPage/dto/atom.interface.tsx

- close #167 
- EndDate Atom 형식 변경

EndDate Atom 형식 변경

---

src/Page/Header/components/Header.tsx
src/Page/MyPage/Atom/atom.tsx

- close #167 
- UserData Atom 수정

UserData Atom 수정

---

src/Page/Stadium/components/Calendar.tsx
src/Page/Stadium/components/Stadium.tsx

- close #186 
- Schedule Month 에러 해결

Schedule Month 에러 해결

---

src/Page/Community/components/Community.tsx
src/Page/Main/components/Main.tsx
src/Page/Reservation/components/Reservation.tsx
src/Page/Scapture/components/Stadiums.tsx
src/Page/Stadium/components/Stadium.tsx
src/apis/dto/scapture.dto.tsx

- close #192 
- Parking -> isFree로 변경

Parking -> isFree로 변경

---

src/Page/MyPage/Admin/components/Stadium/Stadium.tsx

- close #190
- 구장 관리 상세페이지 에러 해결

구장 관리 상세페이지 에러 해결

---

src/Page/MyPage/Admin/components/Camera/CameraControl.tsx
src/apis/api/admin.api.tsx

Socket 설정 변경

---

src/Page/Header/components/Header.tsx
src/Page/Stadium/components/Calendar.tsx
src/Page/Stadium/components/SelectBtn.tsx
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/components/Stadium.tsx
src/Page/Stadium/components/StadiumHours.tsx
src/Page/Stadium/components/VideoList.tsx
src/Page/Stadium/scss/selectInfoBox.module.scss
src/Page/Stadium/scss/stadium.module.scss
src/Page/Video/components/Video.tsx
src/apis/api/mypage.api.tsx
src/apis/api/stadium.api.tsx

- close #203 
- Scapture 페이지 구장 및 영상 조회 플로우에 맞게 수정
- Schedule List가 잘못 나오는 에러 해결

Scapture 페이지 구장 및 영상 조회 플로우에 맞게 수정

---

src/Page/Community/components/Community.tsx
src/Page/Header/components/Header.tsx
src/Page/Video/components/Video.tsx
src/apis/api/mypage.api.tsx
src/apis/api/video.api.tsx

- close #205 
- 좋아요 기능 => 로그인된 사용자가 아닐시 로그인 모달
- 북마크도 위와 동일
- 영상 다운로드 로직 수정
- 공유하기?

Scapture / Community 페이지 영상 관련 기능들 추가 보완

---

src/Page/MyPage/Admin/components/EditStadium/EditBasicInfo.tsx
src/Page/Scapture/components/Scapture.tsx
src/apis/api/stadium.api.tsx

- close #207 
- City, State 리스트 받아오기 개발

위치 리스트 기능 추가

---

src/Page/MyPage/Admin/components/EditStadium/EditField.tsx
src/Page/MyPage/Admin/components/Stadium/Fields.tsx
src/Page/MyPage/Admin/components/Stadium/ManageStadium.tsx
src/Page/MyPage/Admin/components/Stadium/scss/Fields.module.scss
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/components/StadiumHours.tsx
src/Page/Stadium/scss/selectInfoBox.module.scss
src/apis/api/admin.api.tsx
src/index.scss

- close #201 
- 관리자 계정 구장 수정 및 생성하기 임시 조치
- 현재 시간과 가장 가까운 Schedule 선택되게 수정

구장 정보 수정하기 개발 및 shcedule 관련 기능 수정

---

src/Page/Footer/components/Footer.tsx
src/Page/Footer/scss/footer.module.scss
src/Page/Main/components/Main.tsx

- close #210 
- 제휴 문의 및 이용약관 연결
- x

제휴 문의 및 이용약관 연결

---

src/App.tsx
src/Page/Stadium/components/Stadium.tsx

- close #213 
- Stadium URL 접근 허용

Stadium URL 접근 허용

---

src/Page/Scapture/components/Scapture.tsx
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/scss/selectInfoBox.module.scss
src/Page/Stadium/scss/stadium.module.scss

다운로드 문의 버튼 추가

---

index.html

- close #217 
- Google Analytics 코드 위치 수정

📝 Google Analytics 코드 위치 수정

---

src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/scss/selectInfoBox.module.scss

- close #220 
- 다운로드 문의 밑 유의사항 추가

📝 다운로드 문의 밑 유의사항 추가

---

src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/components/StadiumHours.tsx
src/Page/Stadium/scss/selectInfoBox.module.scss
src/Page/Video/components/StadiumHours.tsx
src/Page/Video/components/Video.tsx

- close #220 
- 스케쥴 텍스트 color 변경

스케쥴 텍스트 color 변경

---

src/Page/Stadium/components/StadiumHours.tsx

스케쥴 클릭시 이동 수정

---

src/Page/Stadium/components/Calendar.tsx
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/scss/selectInfoBox.module.scss
src/Page/Video/components/Video.tsx
src/Page/Video/scss/video.module.scss

- close #224 
- 원주 날짜 토일 고정
- 영상 링크 공유 추가
- schedule 선택 안되는 문제 해결

원주 날짜 토일 고정 및 영상 링크 공유 추가

---

src/Page/Stadium/components/Calendar.tsx
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/scss/selectInfoBox.module.scss

- close #226 
- 원주 Calendar 토/일 날짜 고정 해제

원주 Calendar 토/일 날짜 고정 해제

---

src/Page/MyPage/Admin/components/Camera/CameraControl.tsx
src/Page/MyPage/Admin/components/EditProfile/ManagerInfo.tsx
src/Page/MyPage/Admin/scss/adminPage.module.scss

- close #228 
- 녹화 시간 추가 및 디자인 변경

녹화 시간 추가 및 디자인 변경

---

.eslintrc.cjs
index.html
package-lock.json
package.json
src/Page/MyPage/Admin/components/AdminPage.tsx
src/Page/MyPage/Admin/components/Camera/CameraControl.tsx
src/Page/Stadium/components/Stadium.tsx
src/common/component/VideoPlayer.tsx

- close #230 
- HLS 포맷에 DRM이 적용된 영상 재생해보기

HLS 포맷에 DRM이 적용된 영상 재생해보기

---

src/Page/MyPage/Admin/components/AdminPage.tsx
src/common/component/VideoPlayer.tsx

- close #230 
- 브라우저에 맞는 drmType 가져오기

브라우저에 맞는 drmType 가져오기

---

package-lock.json
package.json
src/Page/Community/components/Community.tsx
src/common/component/VideoPlayer.tsx
src/common/scss/video.module.scss

- close #230 
- VideoJS 화질 선택 기능 및 CSS 테스트

VideoJS 화질 선택 기능 및 CSS 테스트

---

package-lock.json
package.json
src/common/component/VideoPlayer.tsx

화질 선택 기능 추가

---

package-lock.json
package.json
src/common/component/VideoPlayer.tsx

- close #230 
- 화질 선택 플러그인 추가
```
npm install videojs-http-source-selector
```

화질 선택 플러그인 추가

---

package-lock.json
package.json
src/common/component/VideoPlayer.tsx

- close #230 
- Videojs 버전 downgrade

Videojs 버전 downgrade

---

package-lock.json
package.json
src/common/component/VideoPlayer.tsx

- close #230 
- Video.js 버전 변경

Video.js 버전 변경

---

package-lock.json
package.json
src/Page/Community/components/Community.tsx
src/Page/MyPage/Admin/components/AdminPage.tsx
src/Page/Video/components/Video.tsx
src/common/component/VideoPlayer.tsx

모든 영상에 DRM 적용

---

src/common/component/VideoPlayer.tsx

- close #241 
- Video src 경로 수정

Video src 경로 수정

---

src/Page/MyPage/Admin/components/Camera/CameraControl.tsx

- close #239 
- 녹화 강제 종료 논리 오류 해결

녹화 강제 종료 논리 오류 해결

---

src/Page/MyPage/Admin/components/Camera/CameraControl.tsx

- close #239 
- 타이머 시간 선택시 formmating

타이머 시간 선택시 formmating

---

src/Page/MyPage/Admin/components/Camera/CameraControl.tsx

- close #239 
- 녹화 종료 확인 기능 추가

녹화 종료 확인 기능 추가

---

src/Page/MyPage/Admin/components/Camera/CameraControl.tsx
src/common/component/VideoPlayer.tsx

- close #239 
- 브라우저에 맞는 drm 제공

브라우저에 맞는 drm 제공

---

index.html

- close #239 
- 애드센스 코드 스니펫 적용

애드센스 코드 스니펫 적용

---

package-lock.json
package.json
src/App.tsx
src/Page/MyPage/MyPage/components/ChargeBanana.tsx
src/Page/MyPage/MyPage/components/SubscribeModal.tsx
src/Page/MyPage/MyPage/components/UserPage.tsx
src/Page/MyPage/MyPage/scss/chargeBanana.module.scss
src/common/component/Payment/PayFail.tsx
src/common/component/Payment/PaySuccess.tsx
src/common/component/Payment/Payments.tsx
src/common/scss/payments.module.scss

- close #252 
- 구독 및 버내너 충전 결제 연결

구독 및 버내너 충전 결제 연결

---

src/Page/MyPage/MyPage/components/ChargeBanana.tsx
src/Page/MyPage/MyPage/scss/chargeBanana.module.scss
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Video/components/VideoModal.tsx

- close #252 
- 결제 연동 및 상품 이용기간 추가

결제 연동 및 상품 이용기간 추가

---

src/Page/MyPage/components/MyPage.tsx
src/apis/api/admin.api.tsx

- close #252 
- 마이페이지에서 새로고침시 로그아웃되는 에러 해결

마이페이지에서 새로고침시 로그아웃되는 에러 해결

---

src/Page/Video/components/Video.tsx

영상 다운로드 경로 변경

---

src/Page/Stadium/components/SelectInfoBox.tsx

- close #252 
- 영상이 있는 경우에만 전체 다운로드 추가

영상이 있는 경우에만 전체 다운로드 추가

---

src/common/component/VideoPlayer.tsx

- close #260 
- Token 생성시 useEffect 사용

Token 생성시 useEffect 사용

---

src/common/component/VideoPlayer.tsx

- close #260 
- Base64Token 확인

Base64Token 확인

---

src/common/component/VideoPlayer.tsx

- close #260 
- Drmtype 구체적으로 나누기

Drmtype 구체적으로 나누기

---

src/common/component/VideoPlayer.tsx

- close #260 
- Os와 브라우저에 맞는 drmtype 조건 추가

Os와 브라우저에 맞는 drmtype 조건 추가

---

src/common/component/VideoPlayer.tsx

- close #260 
- Drm type 옵션 추가

Drm type 옵션 추가

---

src/App.tsx
src/Page/Manager/components/Highlights.tsx
src/Page/Manager/components/Manager.tsx
src/Page/Manager/dto/manager.tsx
src/Page/Manager/scss/manager.module.scss
src/apis/api/manager.api.tsx

- close #255 
- 하이라이트 조회 페이지 제작

하이라이트 조회 페이지 제작

---

src/common/component/VideoPlayer.tsx

- close #270 
- Navigator 기능을 활용한 drmType 자동 감지

Navigator 기능을 활용한 drmType 자동 감지

---

src/common/component/VideoPlayer.tsx

- close #270 
- DrmType에 맞는 video src 설정

DrmType에 맞는 video src 설정

---

src/common/component/VideoPlayer.tsx

- close #270 
- DrmType 자동 감지 기능

DrmType 자동 감지 기능

---

src/common/component/VideoPlayer.tsx

- close # Issue Number
- Log 삭제 및 오타 수정

Log 삭제 및 오타 수정

---

src/common/component/VideoPlayer.tsx

- close #270 
- FairPlay 순서 변경

FairPlay 순서 변경

---

src/common/component/VideoPlayer.tsx

- close #270 
- Ios 기기는 requestMediaKeySystemAccess를 지원하지 않아 예외처리 추가

Ios 기기는 지원하지 않아 예외처리 추가

---

src/common/component/VideoPlayer.tsx

기본 drmtype 설정

---

src/common/component/VideoPlayer.tsx

- close #270 
- 지원하지 않는 os, 브라우저 확인 후 자동으로 체크

지원하지 않는 os, 브라우저 확인 후 자동으로 체크

---

src/Page/MyPage/MyPage/components/ChargeBanana.tsx
src/Page/MyPage/MyPage/components/SubscribeModal.tsx
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Video/components/VideoModal.tsx
src/common/component/Payment/Payments.tsx
src/common/component/image/cancel.svg
src/common/scss/payments.module.scss

- close #252 
- 결제창 OrderName 추가 및 CSS 일부 변경

결제창 OrderName 추가 및 CSS 일부 변경

---

.eslintrc.cjs
src/Page/Header/components/LoginModal.tsx
src/Page/Main/components/Main.tsx
src/Page/MyPage/MyPage/components/ChargeBanana.tsx
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Video/components/VideoModal.tsx
src/apis/api/user.api.tsx
src/apis/config/login.config.tsx
src/common/component/Payment/Payments.tsx
src/common/component/Payment/dto/request.dto.ts
src/common/scss/payments.module.scss
tsconfig.app.json

- close #252 
- 결제 페이지 일부 수정 및 리다이렉트 테스트

결제 페이지 일부 수정 및 리다이렉트 테스트

---

src/Page/Community/components/Community.tsx
src/Page/Manager/components/Bridge/RequestCheckModal.tsx
src/Page/Manager/components/Bridge/RequestSuccessModal.tsx
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Video/components/Video.tsx
src/Page/Video/components/VideoModal.tsx
src/common/component/Payment/Payments.tsx

- close #282 
- 영상 drm 변경 및 결제 시스템 일부 변경

영상 drm 변경 및 결제 시스템 일부 변경

---

src/App.tsx
src/Page/Community/components/Community.tsx
src/Page/Manager/components/Bridge/RequestCheckModal.tsx
src/Page/Manager/components/Highlights.tsx
src/Page/Manager/dto/manager.tsx
src/Page/Manager/scss/manager.module.scss
src/Page/Manager/scss/requestSuccessModal.module.scss
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/components/StadiumHours.tsx
src/Page/Video/components/Video.tsx
src/Page/Video/components/VideoList.tsx

- close #282 
- 리다이렉트 에러 해결
- Schedule 리스트 클릭시 위치 이동 제거
- 실내/실외 에러 해결
- 하이라이트 요청 모달 동작 방식 변경
- 하이라이트 요청 리스트 수정

리다이렉트 에러 해결 및 일부 에러 해결

---

src/App.tsx
src/Page/Community/components/Community.tsx
src/Page/Manager/components/Highlights.tsx
src/Page/Manager/dto/manager.tsx
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Video/components/Video.tsx
src/Page/Video/components/VideoList.tsx
src/Page/Video/components/VideoModal.tsx

- close # Issue Number
- 하이라이트 요청 페이지 정보 추가
- Video 경로 변경 및 다운로드 수정
- 다운로드 로직 수정 및 다운로드 후 데이터 갱신

하이라이트 요청 페이지 및 Video 페이지 수정

---

src/Page/Manager/components/Bridge/ScheduleList.tsx
src/Page/Manager/scss/scheduleList.module.scss

- close #282 
- 브릿지 페이지 요청 비활성화

브릿지 페이지 요청 비활성화

---

index.html

- close #298  
- favicon 경로를 절대경로로 설정하여 favicon 활성화

:bug: fix(index): favicon 절대경로로 변경 (#298)

---

src/App.tsx
src/Page/Community/components/Community.tsx
src/assets/image/Success.svg
src/common/component/Payment/PayFail.tsx
src/common/component/Payment/PaySuccess.tsx
src/common/component/Payment/Payments.tsx
src/common/scss/paySuccess.module.scss

- close #288 
- 결제 성공/실패 UI 제작
- 결제 후 리타이렉트 기능 추가

결제 후 페이지 제작

---

src/Page/Manager/components/Bridge/Bridge.tsx
src/Page/Manager/components/Bridge/ScheduleList.tsx

브릿지 페이지 일시 중단

---

index.html
src/Page/Main/components/Main.tsx

- close #305 
- NAVER SEO 설정 완료
- X

:bug: fix: Naver SEO 완료

---

src/Page/Video/components/Video.tsx

- close #302 
- 테스트를 위해 비활성화 한 다운로드 권한 제어 활성화

테스트를 위해 비활성화 한 다운로드 권한 제어 활성화

---

src/Page/Community/components/Community.tsx
src/Page/Main/components/Main.tsx
src/Page/Manager/components/Bridge/Bridge.tsx
src/Page/MyPage/Admin/components/Stadiums.tsx
src/Page/Scapture/components/Stadiums.tsx
src/Page/Stadium/components/Calendar.tsx
src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/components/Stadium.tsx
src/apis/dto/scapture.dto.tsx

- close #311 
- 실내/실외 에러 해결
- 계룡시 전용 calendar 제작

계룡시 전용 calendar 제작

---

src/Page/Scapture/components/Scapture.tsx
src/Page/Stadium/components/Calendar.tsx

- close #311 
- 계룡 전용 Calendar 제작

계룡 전용 Calendar 제작

---

src/Page/Community/components/Community.tsx
src/Page/Manager/components/Bridge/Bridge.tsx
src/Page/Manager/components/Bridge/ScheduleList.tsx
src/Page/Video/components/Video.tsx
src/Page/Video/components/VideoModal.tsx
src/apis/api/video.api.tsx

- close #316 
- 브릿지 페이지 수정
- 버내너 할인 적용

브릿지 페이지 수정 및 버내너 할인 적용

---

src/Page/Manager/components/Bridge/Bridge.tsx
src/Page/Manager/components/CheckHighlights/Highlights.tsx
src/common/component/AlertModal.tsx
src/common/component/DRMPlayer/NaverVideoPlayer.tsx
src/common/scss/alertModal.module.scss

- close #314 
- DRM 세팅 및 브릿지 모달 수정

DRM 세팅 및 브릿지 모달 수정

---

src/Page/Community/components/Community.tsx
src/Page/Main/components/Main.tsx
src/Page/Scapture/components/Scapture.tsx
src/Page/Stadium/components/Stadium.tsx

- close #324 
- SEO 재설정 및 한글 검색 활성화 시도
- X

SEO 재설정 및 한글검색 활성화

---

src/Page/Scapture/components/Scapture.tsx
src/Page/Scapture/components/SelectBtn.tsx
src/Page/Scapture/components/Stadiums.tsx
src/apis/api/scapture.api.tsx

- close #323 
- Scapture 페이지 기능 변경

Scapture 페이지 기능 변경

---

src/Page/Manager/components/CheckHighlights/Highlights.tsx
src/Page/Manager/scss/manager.module.scss

하이라이트 추출 구분

---

src/Page/Manager/scss/manager.module.scss

- close #323 
- 추출 완료일시 텍스트 색상 변경

추출 완료일시 텍스트 색상 변경

---

src/Page/MyPage/MyPage/components/UserPage.tsx
src/Page/Video/components/Video.tsx
src/Page/Video/image/beforeBtn.svg
src/Page/Video/image/nextBtn.svg
src/Page/Video/scss/video.module.scss
src/apis/dto/myPage.dto.tsx
src/apis/dto/scapture.dto.tsx

- close #333 
- 영상 넘기기 버튼 추가 및 저장한 영상 route url 변경

영상 넘기기 버튼 추가 및 저장한 영상 route url 변경

---

src/Page/Video/components/Video.tsx
src/Page/Video/scss/video.module.scss

- close #333 
- 영상 넘기기 버튼 크기 수정

영상 넘기기 버튼 크기 수정

---

src/App.tsx
src/Page/Manager/components/CheckHighlights/Highlights.tsx
src/Page/Manager/components/CheckHighlights/Manager.tsx
src/Page/Manager/components/CheckHighlights/ManagerOptPage.tsx
src/Page/Manager/components/CheckHighlights/UserDetailInfo.tsx
src/Page/Manager/components/CheckHighlights/UserInfoManage.tsx
src/Page/Manager/dto/userInfo.dto.ts
src/Page/Manager/scss/manager.module.scss
src/apis/api/manager.api.tsx

- close #338 
- 회원 관리 관리자 페이지 생성

회원 관리 관리자 페이지 생성

---

src/Page/Community/components/Community.tsx
src/Page/Video/components/Video.tsx
src/common/component/DRMPlayer/NaverVideoPlayer.tsx

- close #314 
- Pallycon drm 적용

Pallycon drm 적용

---

src/Page/Community/components/Comment.tsx
src/Page/Community/scss/community.module.scss
src/apis/api/community.api.tsx

신고 기능은 API 만들어지고 나서 추가 예정
- close #342 
- 댓글 삭제 / 신고 기능 추가, 신고 기능은 추후 API 개발 완료 된 후 추가 작업 필요

✨ feat: 댓글 삭제 기능 추가

---

src/Page/Community/components/Comment.tsx
src/Page/Community/scss/community.module.scss

내 댓글 - 삭제/신고 드롭다운
내 댓글 X - 신고 드롭다운
- close # Issue Number
- (작업 설명을 작성해 주세요.)
- (참고 해야할 코드, 변경 사항은 commit url로 작성 해주세요.)

✨ feat: 댓글 삭제 / 신고 업데이트

---

.eslintrc.cjs
package-lock.json
src/common/component/VideoPlayer.tsx

- close #348 
- Fairpaly DRM 적용

Fairpaly DRM 적용

---

src/Page/Video/scss/video.module.scss

- close #348 
- Video 잘리는 현상 해결

Video 잘리는 현상 해결

---

src/Page/Community/components/Community.tsx
src/Page/Community/scss/community.module.scss

- close #352 
- 커뮤니티 영상 존재하지 않을시

커뮤니티 영상 존재하지 않을시

---

src/Page/Video/components/Video.tsx

- close #352 
- 하이라이트 요청자만 다운로드 가능

하이라이트 요청자만 다운로드 가능

---

index.html
src/common/component/VideoPlayer.tsx

- close #352 
- 고화질 자동 선택 및 재생 버튼 위치 변경

고화질 자동 선택 및 재생 버튼 위치 변경

---

src/Page/Stadium/components/SelectInfoBox.tsx

년도 구분하게 변경

---

src/Page/Footer/components/Footer.tsx

- close #361 
- Footer Email 변경

Footer Email 변경

---

src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/components/VideoList.tsx
src/Page/Video/components/Video.tsx

- close #363 
- 풀경기 영상 다운로드 요청자만 가능하게 변경

풀경기 영상 다운로드 요청자만 가능하게 변경

---

src/Page/Stadium/components/SelectInfoBox.tsx
src/Page/Stadium/components/Stadium.tsx
src/Page/Stadium/components/VideoList.tsx

- close #363 
- IsDownloadableOriginVideo null 형식 추가

IsDownloadableOriginVideo null 형식 추가

---

src/App.tsx
src/Page/Manager/components/CheckHighlights/CheckOriginalVideos.tsx
src/Page/Manager/components/CheckHighlights/Highlights.tsx
src/Page/Manager/components/CheckHighlights/Manager.tsx
src/Page/Manager/dto/manager.tsx
src/Page/Manager/scss/manager.module.scss
src/apis/api/manager.api.tsx

- close #352 
- Manager 원본 영상 다운 기능 추가

Manager 원본 영상 다운 기능 추가

---

src/Page/MyPage/Admin/components/Camera/CameraControl.tsx

- close #372 
- 구역 변경시 원본 영상 리스트 변경

구역 변경시 원본 영상 리스트 변경
